CREATE TABLE authorities
(
    username  VARCHAR(255) NOT NULL,
    authority VARCHAR(255) NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (username)
);

CREATE TABLE todo
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    megnevezes VARCHAR(255)                            NOT NULL,
    hatarido   VARCHAR(255)                            NOT NULL,
    kesz       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_todo PRIMARY KEY (id)
);

CREATE TABLE users
(
    username  VARCHAR(255) NOT NULL,
    nev       VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    profilkep VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

ALTER TABLE todo
    ADD CONSTRAINT FK_TODO_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);